# Numpy

In [15]:
import numpy as np # import lib

In [184]:
a = np.arange(15)

a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [185]:
b = a.reshape(5, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [186]:
b.shape

(5, 3)

In [187]:
b.ndim # number dimention

2

In [188]:
a.dtype.name # data type of 'a'

'int32'

In [189]:
b.size # size of array 'b'

15

In [190]:
type(b) # type of b

numpy.ndarray

In [191]:
x = np.array([1, 10, -2]) # create array
x

array([ 1, 10, -2])

In [192]:
y = np.array([(1, 2, 3), (4, 6, 0)])
y

array([[1, 2, 3],
       [4, 6, 0]])

In [193]:
np.zeros((2, 6)) # create array of zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [194]:
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [195]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [196]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
np.arange(0, 2, 0.1) # array of number inrement by 0.1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [198]:
np.linspace(0, 5, 10) # divise array to size 10 in range[0, 5]

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [199]:
from numpy import pi # or np.pi
pi

3.141592653589793

In [200]:
np.linspace(0, 2*pi, 5)

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [201]:
np.cos(b)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722]])

In [202]:
a = np.array([1, 2, 3])
b = np.array([3, 0, 9])
a - b

array([-2,  2, -6])

In [203]:
a * b

array([ 3,  0, 27])

In [204]:
b**2

array([ 9,  0, 81], dtype=int32)

In [205]:
15 * np.sin(a)

array([12.62206477, 13.6394614 ,  2.11680012])

In [206]:
a = np.ones((2, 3), dtype=int)
a * 3

array([[3, 3, 3],
       [3, 3, 3]])

#### Random

In [207]:
b = np.random.random((2, 4))
b

array([[0.0920335 , 0.77639303, 0.56104146, 0.15551269],
       [0.3622826 , 0.47236111, 0.6605102 , 0.51871511]])

In [208]:
b.sum()

3.5988497025946087

In [209]:
print("max: ", b.max(), " min: ", b.min()) # get max & min in array

max:  0.7763930295684058  min:  0.09203350386697273


In [210]:
b

array([[0.0920335 , 0.77639303, 0.56104146, 0.15551269],
       [0.3622826 , 0.47236111, 0.6605102 , 0.51871511]])

In [211]:
b.sum(axis=0) # sum of column

array([0.4543161 , 1.24875414, 1.22155166, 0.6742278 ])

In [212]:
b.sum(axis=1) # sum by rows

array([1.58498068, 2.01386902])

In [213]:
b.cumsum(axis=1)

array([[0.0920335 , 0.86842653, 1.42946799, 1.58498068],
       [0.3622826 , 0.83464371, 1.49515391, 2.01386902]])

In [214]:
a = np.arange(10) ** 2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [215]:
a[3]

9

In [216]:
a[1:4]

array([1, 4, 9], dtype=int32)

In [217]:
a[-1] # get last element

81

In [218]:
b

array([[0.0920335 , 0.77639303, 0.56104146, 0.15551269],
       [0.3622826 , 0.47236111, 0.6605102 , 0.51871511]])

In [219]:
for row in b:
    for i in row:
        print(i, end=" ")
    print()

0.09203350386697273 0.7763930295684058 0.5610414575364044 0.15551268721445222 
0.3622825979818858 0.47236111118359825 0.6605102035287517 0.5187151117141381 


In [220]:
for i in b.flat:
    print(i)

0.09203350386697273
0.7763930295684058
0.5610414575364044
0.15551268721445222
0.3622825979818858
0.47236111118359825
0.6605102035287517
0.5187151117141381


In [222]:
b

array([[0.0920335 , 0.77639303, 0.56104146, 0.15551269],
       [0.3622826 , 0.47236111, 0.6605102 , 0.51871511]])

In [232]:
b.ravel()

array([0.0920335 , 0.77639303, 0.56104146, 0.15551269, 0.3622826 ,
       0.47236111, 0.6605102 , 0.51871511])

In [241]:
b.shape = (4, 2)
b

array([[0.0920335 , 0.77639303],
       [0.56104146, 0.15551269],
       [0.3622826 , 0.47236111],
       [0.6605102 , 0.51871511]])

In [243]:
b.T # matrice transposé

array([[0.0920335 , 0.56104146, 0.3622826 , 0.6605102 ],
       [0.77639303, 0.15551269, 0.47236111, 0.51871511]])

In [247]:
x

array([ 1, 10, -2])

In [248]:
y

array([[1, 2, 3],
       [4, 6, 0]])